import './globals.css';
import Navbar from '@/components/Navbar';
import SessionAuthProvider from '@/context/SessionAuthProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className='bg-zinc-800'>
        <SessionAuthProvider>
          <Navbar />
          {children}
        </SessionAuthProvider>
      </body>
    </html>
  )
}
